Modify erratacheck.py so it works when there are no errata.
Set the sequence member variable of MyHTMLParser to 0 instead of None
so that it does not error when there are no errata available for a
release, yet.

Fixes the following:

Traceback (most recent call last):
  File "/home/jason/bin/erratacheck", line 92, in <module>
    parser.feed(u.read())
  File "/usr/local/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 163, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 401, in parse_endtag
    self.handle_endtag(elem)
  File "/home/jason/bin/erratacheck", line 50, in handle_endtag
    if int(self.sequence) > self.last_sequence:
TypeError: int() argument must be a string or a number, not 'NoneType'